### Get translated Pokemon information - Legendary (Yoda translation)
GET {{host}}/pokemon/translated/mewtwo
Accept: application/json

###

### Get translated Pokemon information - Cave habitat (Yoda translation)
# Expected: Yoda translation because habitat is "cave"
# Original: "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets."
GET {{host}}/pokemon/translated/zubat
Accept: application/json

###

### Get translated Pokemon information - Regular (Shakespeare translation)
GET {{host}}/pokemon/translated/pikachu
Accept: application/json

###

### Get translated Pokemon information - Ditto (Shakespeare translation)
GET {{host}}/pokemon/translated/ditto
Accept: application/json

###

### Get translated Pokemon information - Case insensitivity test
GET {{host}}/pokemon/translated/ZUBAT
Accept: application/json

###

### Get translated Pokemon information - Mixed case test
GET {{host}}/pokemon/translated/MewTwo
Accept: application/json

###

### Error: Non-existent Pokemon (404)
GET {{host}}/pokemon/translated/notexistingpokemon
Accept: application/json

###

### Error: Empty Pokemon name (404)
GET {{host}}/pokemon/translated/
Accept: application/json