services:
  pokedex-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokedex-api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production